apiVersion: v2
name: nks-newsfeed
description: A Helm chart for NKS Newsfeed Spring Boot Application
type: application
version: 0.1.0
appVersion: "0.0.1-SNAPSHOT"

dependencies:
- name: mysql
  version: 9.4.6
  repository: https://charts.bitnami.com/bitnami
  condition: mysql.enabled
- name: rabbitmq
  version: 11.1.3
  repository: https://charts.bitnami.com/bitnami
  condition: rabbitmq.enabled