spring:
  application:
    name: friend-api
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: password
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin

server:
  port: 8085

feign:
  user-api:
    url: http://localhost:8081