spring:
  application:
    name: user-api
  data:
    redis:
      host: localhost
      port: 6379
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin

jwt:
  secret: your-secret-key-must-be-at-least-256-bits-long-for-HS256-algorithm
  validity-in-seconds: 3600