server:
  port: 8080

spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  cloud:
    compatibility-verifier:
      enabled: false

logging:
  level:
    org.springframework.cloud.gateway: DEBUG