version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: nks-newfeed-rabbitmq
    ports:
      - "5672:5672"   # AMQP port
      - "15672:15672" # Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
      - rabbitmq-plugins:/plugins
    networks:
      - nks-newfeed-network
    command: >
      sh -c "wget -P /plugins https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/releases/download/v3.13.0/rabbitmq_delayed_message_exchange-3.13.0.ez &&
             rabbitmq-plugins enable rabbitmq_delayed_message_exchange &&
             rabbitmq-server"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  rabbitmq-data:
  rabbitmq-plugins:

networks:
  nks-newfeed-network:
    driver: bridge