services:
  neo4j:
    image: neo4j:5-community
    container_name: nks-newfeed-neo4j
    ports:
      - "7474:7474"   # HTTP port
      - "7687:7687"   # Bolt port
    environment:
      NEO4J_AUTH: neo4j/password
      NEO4J_dbms_memory_pagecache_size: 512M
      NEO4J_dbms_memory_heap_initial__size: 512M
      NEO4J_dbms_memory_heap_max__size: 1G
    networks:
      - nks-newfeed-network
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:7474 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  nks-newfeed-network:
    driver: bridge