# ArgoCD 설치를 위한 namespace 및 기본 설정
apiVersion: v1
kind: Namespace
metadata:
  name: argocd
---
# ArgoCD 설치 (공식 매니페스트 사용)
# kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml

# ArgoCD Server Service를 LoadBalancer로 변경 (NKS ALB 사용)
apiVersion: v1
kind: Service
metadata:
  name: argocd-server-lb
  namespace: argocd
  annotations:
    ncloud.com/load-balancer-type: "nlb"  # NKS Network Load Balancer
spec:
  type: LoadBalancer
  ports:
  - name: server
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: grpc
    port: 443
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: argocd-server