apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis-cluster
  namespace: argocd
  labels:
    app.kubernetes.io/name: redis-cluster
    app.kubernetes.io/component: database
spec:
  project: default
  source:
    repoURL: https://github.com/SeonghaeJo/nks-newsfeed.git
    targetRevision: main
    path: helm/redis-cluster
    helm:
      valueFiles:
      - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: nks-infrastructure
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  ignoreDifferences:
  - group: apps
    kind: StatefulSet
    jsonPointers:
    - /spec/replicas
    - /spec/template/spec/containers/0/resources