apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis-cluster.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "redis-cluster.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: redis
    protocol: TCP
    name: redis
  - port: {{ .Values.service.clusterPort }}
    targetPort: cluster
    protocol: TCP
    name: cluster
  selector:
    {{- include "redis-cluster.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis-cluster.fullname" . }}-headless
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "redis-cluster.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
  - port: {{ .Values.service.port }}
    targetPort: redis
    protocol: TCP
    name: redis
  - port: {{ .Values.service.clusterPort }}
    targetPort: cluster
    protocol: TCP
    name: cluster
  selector:
    {{- include "redis-cluster.selectorLabels" . | nindent 4 }}